# Configures rkt tests at Travis CI (https://travis-ci.org).

language: go

go:
 - 1.4

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools

install:
 - go get golang.org/x/tools/cmd/cover
 - go get golang.org/x/tools/cmd/vet

script:
 - ./configure
 - make stage0-test SHELL="/bin/bash -v"
